//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallPool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int MatchID { get; set; }
        public int MatchWeekID { get; set; }
        public string LocalTeam { get; set; }
        public string VisitorTeam { get; set; }
        public int LocalScore { get; set; }
        public int VisitorScore { get; set; }
    
        public virtual MatchWeek MatchWeek { get; set; }
    }
}
