//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallPool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchPool
    {
        public int MatchPoolID { get; set; }
        public int MatchWeekID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> LocalScore { get; set; }
        public Nullable<int> VisitorScore { get; set; }
        public int Score { get; set; }
        public string IsSaved { get; set; }
        public int PoolID { get; set; }
        public int MatchID { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual User User { get; set; }
    }
}
